### ISSUE TITLE
Throwing the horns

### ISSUE THREAD

**Issue by chrisbuttery** [scottcorgan/awesome-elm-metal#5]
I'm wondering if we should add something like this? Just for giggles.

![elm-metal](https://cloud.githubusercontent.com/assets/121675/16262593/9a7ee834-38b3-11e6-896a-4e03aaf88be7.png)

**Comment by scottcorgan** [comment]
I love that! Open a PR!!

**Comment by scottcorgan** [comment]
Looks like you already opened a PR. What's the reason you closed it?

**Comment by kvnneff** [comment]
ha!  sick

**Comment by rtfeldman** [comment]
![gimme-fue-gimme-fai-gimme-dabajabaza](https://cloud.githubusercontent.com/assets/1094080/16275298/4a21d9fa-385e-11e6-9f58-ddb365581605.jpg)

**Comment by chrisbuttery** [comment]
@scottcorgan Yeah originally I add a basic `elmtagram`\- but then I thought I could do better. So I closed that and made sure you folks liked this one 👍
